package:
  name: fastcov
  version: 0.1.3

build:
  number: 0

source:
  fn: 0.1.3.tar.gz
  url: https://github.com/RaverJay/fastcov/archive/refs/tags/0.1.3.tar.gz
  md5: 'a8b73898296641a215748c9426abb125'

requirements:
  run:
    - python
    - matplotlib==3.8.3
    - pandas==2.2.1
    - pysam==0.22.0
    - seaborn==0.13.2

test:
  commands:
    - fastcov -h
    - fastcov.py -h

about:
  home: https://github.com/RaverJay/fastcov
  license: MIT
  summary: This package installs fastcov and all it's dependencies. fastcov is used to plot coverage plots based on BAM files.